### ISSUE TITLE
Custom Download for F6 - Issues...

### ISSUE THREAD

**Issue by LDigital84** [zurb/foundation-sites#7033]
From what I can tell there isn't a way to select and use the Flexbox grid if you use the [Custom Download](http://foundation.zurb.com/sites/download.html/) tool.

Am I missing something and there is there a way to do this? 

If not, this option needs to be available. 

List of issues with the Customizer and Customizer Page: 
- [x] ~~No way to select Flexbox Grid~~
- [x] Error in the console saying jQuery is not defined. (In Firefox, Chrome does not throw a jQuery error.) 
- [x] JS Error: `SyntaxError: function statement requires a name templates.js:1:8`
- [x] ~~The max-width is set to 62.5rem on the customizer page, however, the download max-width is 75rem. Colors are also different.~~
- [x] The link at the top of the page (in the top bar) for Docs is broken on the customizer page. 
- [x] ~~In the foundation.js (and min.js) file the version is listed as 6.0.0-alpha.1.~~
- [x] In the foundation.js (and min.js) file the version is 6.0.1. Should be 6.0.4.
- [x] When I unzip (using 7zip) the custom download I see this error: `Data error in 'custom-f6\app.css'. File is broken`. Other files appear okay.
- [x] If you select the Flex Grid and no other items, the customizer only downloads the normalize CSS and nothing else.
- [x] Some downloads are missing `foundation.css` #7520 #7702
- [x] Gutter size can't be changed #7593
- [x] Essentials missing the grid #7753
- [x] Selecting "No Grid" results in a missing `foundation.css` file #7819
- [x] Add field to change `$warning-color` #7858
- [ ] Checkbox state can go out of whack when manipulating the "All Foundation Components" checkbox #7820
- [x] 7 digits can be entered into the color fields #8061

**Comment by Lynda333** [comment]
Few other things I noticed on the customizer page. 

1) Error in the console saying jQuery is not defined. 

2) It appears the max-width is set to 62.5rem in the download page, however, the download max-width is 75rem. 

3) The link at the top of the page for Docs is broken on the customizer page.

**Comment by joomlolo** [comment]
Hello,
with firefox 42.0 :
"Choose Your Components:"
"All Foundation Components"
the checkbox unchecked doesn't uncheck all foundation component, no change checked or unchecked
with chrome Version 46.0.2490.86 no problem

**Comment by Lynda333** [comment]
@joomlolo - It's because jQuery works in Chrome but not Firefox.

**Comment by gakimball** [comment]
Paging @erikmellum

**Comment by erikmellum** [comment]
* Fixed issue with jquery not being defined
* Fixed doc link at top of page
* Fixed auto updater for customizer
* Tested 7zip in windows without any errors
* Tested and fixed issue with flex grid being selected by itself

Still doing some testing to work through template.js and foundation.js errors.

**Comment by Lynda333** [comment]
@erikmellum - Thanks for fixing these problems. 

Three things:

 - It was my version of 7zip. I checked and updated my version of 7zip and there are no errors now.
 - Typically when you uncheck `All Foundation Components` it unchecks the other boxes as well. This doesn't happen currently. 
 - If you have Grid and Flex Grid both checked it will use the default Grid. It would be great to either use radio buttons or you can only check one but not both to eliminate confusion.

Thank You!

**Comment by erikmellum** [comment]
@Lynda333

We will be switching those to radio buttons. You're definitely right about that! Also, I will look into seeing why the `All Foundation Components` checkbox doesn't work in all browsers. Keep letting me know if you find other things, it's super helpful :).

Thanks,
Erik

**Comment by Lynda333** [comment]
@erikmellum 

Thank you. The customizer page is looking awesome!

I had Edge open and saw this error: 

`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR): GET - http://foundation.zurb.com/sites/download.html/javascripts/jquery.min.map` 

I don't see it in other browsers and don't see any problems in Edge.

On the `All Foundation Components` checkbox. I've noticed that in Chrome and Edge you are using Equalizer to align the buttons at the top. This doesn't run in Firefox. I wonder if JS isn't executing in Firefox for some reason? Maybe because of the template.js error?

**Comment by erikmellum** [comment]
@Lynda333,

I have looked into `All Foundation Components` checkbox problems in Firefox, and don't have a fix quite yet. The code basically looks for the nearest parent div with a class of row, and then searches for all inputs of type checkbox and inverts their checked attribute. I am suspicious that the way Firefox handles the checked attribute is different, but havn't verified the true cause yet. I'll update here when I have a fix. 

Also I am looking in to the template.js error. No updates on that one yet either, but there should be soon.

Erik

**Comment by gakimball** [comment]
Updated the main comment to roll in other issues: #7753 #7702 #7593 #7520

**Comment by gakimball** [comment]
All of the issues in the first comment have been addressed :) Thanks for your patience, y'alls.

**Comment by Lynda333** [comment]
@gakimball - The JS Error `SyntaxError: function statement requires a name        templates.js:1:8` still happens in FireFox. Also, when you check or uncheck `All Foundation Components` it doesn't do anything to the other checkboxes (again in Firefox). The other browsers appear to work okay.

**Comment by erikmellum** [comment]
@gakimball I believe the templates.js error will be resolved when the HTML is moved from the customizer, into the marketing site. I can confirm `All Foundation Components` checkbox doesn't work in Firefox. Not sure what the deal is there.

**Comment by gakimball** [comment]
Reopening for #7820, #7858, and #7819

**Comment by henrymilleruk** [comment]
Waiting for the Custom Download functionality to work again! Cheers!

**Comment by erikmellum** [comment]
@gakimball I will take a look at this when I get home this evening.

**Comment by gakimball** [comment]
@erikmellum Thanks, friend!

**Comment by Benboe** [comment]
@erikmellum  yeah, thanks mate :)

**Comment by howks** [comment]
Why authors remove custom download for F5. In F5 custom download had no bug - everything worked. Now we have nothing. In F6 custom download not working and F5 custom download is gone.

**Comment by erikmellum** [comment]
@howks apologies for the inconvenience. We understand it can be frustrating when things break. We didn't anticipate interest in the F5 custom downloader once F6 was released, which was a bit of an oversight.

Foundation 6.1.2 has some changes that are affecting the custom download. My suspicion is that you would rather have Foundation 6.1.1 than Foundation 5. I think the longer term solution here will be to fall back to the previous version in the event an update breaks the custom downloader. 

We make no excuses for this, but understand that maintaining these things requires man hours and money, and ZURB also has many other projects. We will do our best to prevent this in the future, and get the fix out ASAP. Please be patient with us as we fix this, and thank you for the feedback!

**Comment by rafibomb** [comment]
@howks The custom download was working up until now. Looks like an error occurred over the weekend. It will be up soon.

**Comment by Lynda333** [comment]
@erikmellum - I like that idea about the fallback! That would be a great solution. If possible, when it does fallback, somehow alert the user that it's falling back.

Also, yourself and the team at ZURB do an awesome job! Always appreciated the work that you all do on Foundation!

**Comment by erikmellum** [comment]
@gakimball custom, essential, and complete downloads are fixed. We replaced minifyCss with cssnano, but never updated the gulp task for the customizer (gulp deploy:custom). Always nice when it's something so straight forward! 

Let me know if anything else causes trouble.

**Comment by Lynda333** [comment]
@erikmellum - I noticed a couple things with the custom download...before I go into them, I read your comment about the fix in the development branch. When 6.1.3 is released then it may fix these problems. If that is the case, then you can ignore this comment. 

Here are the problems: 

 -  There are three CSS files downloaded. `app.css`, `foundation.css` and `foundation-flex.css`. Typically, you have three but one of those is the `foundation.min.css` file. the `foundation.css`, and `foundation-flex.css` appear to be identical as I selected the flex grid. If you select the regular grid you still get both files but one file is the float grid while the `foundation-flex.css` is the flex grid.
 - The CSS folder contains the `.map` files for both the `foundation.css` and `foundation-flex.css` files.
 - There is no minifed foundation.min.js. Just the regular, unminified, version.

With that said, I don't mind using the un-minifed JS (it's not hard to minify myself) and the CSS, I typically use unminifed anyway (until production when I minify all of my CSS together.)

**Comment by erikmellum** [comment]
@Lynda333 Excellent catch. 
* The extra .css files are removed
* The .map files are not intended to be there for the custom download (they are removed now)
* The minified files are all intact now

All of those stemmed from a typo when I made when modifying the gulpfile on the server. Sort of a snowball you might say ;). Let me know if you find anything else!

**Comment by Lynda333** [comment]
@erikmellum - Don't you love typos? :smile: The download looks good.

**Comment by joomlolo** [comment]
thanks a lot @erikmellum

**Comment by Benboe** [comment]
@erikmellum thanks very much for the hard work you put into this great project!! :-)

**Comment by howks** [comment]
@erikmellum thanks!
![Working](http://www.reactiongifs.us/wp-content/uploads/2013/07/its_working_star_wars.gif)

**Comment by joomlolo** [comment]
ok ok select or unselect "ALl foundation component", it is not working for me in firefox last version, just for chrome last version and ie11 it is working, but all have no background color for "colors" field, there was before.

**Comment by badcat** [comment]
Yes, the download page exports are generally out of sync :(
http://foundation.zurb.com/sites/download.html/

Complete: 6.1.1 for Foundation and Flex, js
Essential: 6.1.2 for Foundation and Flex, js
Custom: 6.1.2 for Foundation and Flex, js  (using defaults)

How can we keep these synced?

**Comment by Lynda333** [comment]
@erikmellum - I just downloaded the files using the custom downloader and the files are like there were before: 
 - There are three CSS files downloaded. app.css, foundation.css and foundation-flex.css.
 - The CSS folder contains the .map files for both the foundation.css and foundation-flex.css files.
 - There is no minifed foundation.min.js. Just the regular, unminified, version.

**Comment by erikmellum** [comment]
Will take a look this evening

**Comment by erikmellum** [comment]
Fixed all issues. I'm going to carve out some time to rewrite some of the customizer with a different approach using some of the lessons learned. The goal will be to resolve some of these reoccurring issues.

**Comment by henrymilleruk** [comment]
Just wanted to confirm any **Custom downloads** are still just outputting a blank app.css and no other CSS files. 

Eagerly awaiting a fix for my projects! Thanks!

**Comment by erikmellum** [comment]
@henrymilleruk what options are you using on the custom download? The one known issue is that selecting "No Grid" will break the downloader. Other customizations as far as I know should be working.

**Comment by henrymilleruk** [comment]
Indeed - I am selecting 'No Grid'! I'm looking to get all of the "plugins" to use within another grid system that I'm being forced to use.
 
(ie: Sticky, Interchange, Abide,  Equalize etc ... )

**Comment by erikmellum** [comment]
@henrymilleruk I will be rolling out a fix for the no grid issue by tomorrow. I'll have it going for you soon, thanks for your patience!

**Comment by henrymilleruk** [comment]
@erikmellum Thank you sir, appreciate your work.

**Comment by erikmellum** [comment]
@henrymilleruk no grid option has been fixed. I hope that helps your project!

**Comment by erikmellum** [comment]
@gakimball added field to change warning color, and added warning button to HTML template for custom, essential, and complete downloads. 

Fixed glitch allowing 7 characters to be entered into hex fields

**Comment by Silvester20** [comment]
@erikmellum Thanks for adding the warning button to the custom download. Finally the custom download is working as it should be.

@ Zurb Team and contributers
Thanks for the all great work you have done, really awesome!

**Comment by Benboe** [comment]
I really hate to say this, but I'm afraid the custom download is broken again :-(

I don't seem to get a foundation css file or foundation minified js file in my zip file.

If you download on the customize page, without changing any settings, all the files are included, but if you change the max-width, grid and colours, the download doesn't include all the files it seem!

**Comment by Lynda333** [comment]
I can confirm it's broken again. It works but the min files are missing and the map files are visible.

**Comment by erikmellum** [comment]
The problem lies in the minifyCss->cssnano change not being in the master branch. The change keeps being overwritten locally when it polls the git repo to see if it is up to date. I will implement a fix tonight. This should resolve as soon as the develop branch is merged into master

**Comment by erikmellum** [comment]
@Benboe I'd hate for you to not tell us! I replaced the reference to minifyCss again, and also hopefully provided the coupe de gras. To make sure, I manually executed the git pull. It properly refused to update, but I'd like to keep the guard up. Please report if this behavior occurs again and we will turn off the git pull until the minifyCss change is in master.

Thanks everyone!

**Comment by Benboe** [comment]
@erikmellum  thanks again for responding so fast :)

So, is it supposed to work already? Or not yet? Because I tried and I'm still missing my foundation css file, I do however get a foundation.min.js file ;-) Also, in the vendor directory, there are only 2 files.

This is when i change the max-width, gutter-width and colours, using a flex-grid and leaving all the components checked!

**Comment by erikmellum** [comment]
I'm fairly certain gutter-width is the problem, I've seen one other issue where gutter-width is referenced. I will take a look at those configurations this evening and provide a fix. Apologies for the inconvenience, and thank you for providing the configuration in question :).

**Comment by Benboe** [comment]
@erikmellum thanks mate :-)

**Comment by erikmellum** [comment]
@gakimball is there a way to use a single value for gutters? Otherwise we will have to add a second input field so that users on the customizer can specify two sizes (small and medium) for the responsive gutter. Alternatively we could remove the gutter from the customizer altogether.

```scss
$grid-column-responsive-gutter: (
  small: 20px,
  medium: 30px,
);
```

@Benboe apologies for the delay in getting to this. I left my charger back home and wasn't able to do work on it as soon as expected. I'm going to defer to @gakimball on the best course of action. Once I get some input from him I will be happy to implement the chosen functionality.

**Comment by gakimball** [comment]
@erikmellum In 6.2 (which will be out at the end of next week), `$grid-column-gutter` will accept a single value *or* a map, so the customizer should just assign to that value no matter what. You can ignore `$grid-column-responsive-gutter`.

**Comment by erikmellum** [comment]
@Benboe given the imminent release of version 6.20, I am going to hold off on the gutter changes. Once 6.20 releases next week it should be configurable once again. Apologies for any inconvenience that may cause.

**Comment by Benboe** [comment]
@erikmellum thanks for the info!

Do you have a specific date when everything will work again? I can't possibly imagine that I'm the only one who frequently uses the custom settings?
![screen shot 2016-02-25 at 13 51 58](https://cloud.githubusercontent.com/assets/3709877/13320229/995ce2d8-dbc7-11e5-85f1-54ae07430748.png)

I don't know if it helps, but I added a screenshot of the settings I enter that make the download break.

**Comment by erikmellum** [comment]
@Benboe it looks like both your success and alert color are using only 5 characters which will break the downloader. Other than that, I tried your settings and they seem to work.

I am hoping the issue with gutter will be fixed by the end of the weekend.

**Comment by gakimball** [comment]
@erikmellum For the gutter stuff:

`$grid-column-gutter` is now the *only* way to set gutters. It accepts either a single numeric value, or a map. So for the customizer, you can pass it a number and everything will work fine.

**Comment by Benboe** [comment]
@erikmellum ouch! sorry man!! that's so stupid of me, that'll teach me to copy paste the code without double-checking 

thanks again so much for your hard work!! really appreciate it!

**Comment by Lynda333** [comment]
@erikmellum @gakimball - Any idea on when this may work again? I know you donate your time and not trying to be a bother. Just curious. Thank you for all you do!

**Comment by Benboe** [comment]
First of all @erikmellum  thanks so much for this great project :-)

Having said that, I'm about to start some new projects and I really would need the custom downloads as I really wanna use foundation.

Is there an estimate of when this will work again?

**Comment by erikmellum** [comment]
Hello all, 

Sadly I don't have an estimate for when the customizer will be fixed. My license for VMWare expired, which is what I was using to maintain the customizer. I will be doing my best to set up a new VM dev environment using virtualbox, but I'm unsure when that will be completed. ZURB is working towards a solution so I will defer further questions to @gakimball.

**Comment by Lynda333** [comment]
@erikmellum - Thank you for the info. I think ZURB should buy you a new license for VMWare. :smiley:

**Comment by Benboe** [comment]
I agree ^_¨

But from what I've seen the last months however, sometimes I have a feeling Foundation is coming to an end, I hope I'm wrong here.. It's just a feeling I have..

The custom download has been very very unstable and now even just not available anymore since quite a while.  And (perhaps I'm doing something wrong?) but I can't get the accordion to work out of the box, also when I download the full package (which is the only choice now), it doesn't include all the seperate .js-files anymore (like accordion).

It looks like ZURB doesn't really care that much anymore? :-(

**Comment by rafibomb** [comment]
Totally hear you about the customizer! It's been unreliable since we launched F6 and recently broke when 6.2 was released. It is requiring a re-build which is what we're working on now. We are planning to have it squared away by the end of the month.

@Benboe As far as the accordion issue you mentioned, if there is already an open issue for it we'd like to see it for the next release.

**Comment by gakimball** [comment]
Hey friends! Thanks for your patience. We've been weighing some options about how to stabilize the customizer, and we've arrived at a solution. We plan on having it done in the next week or so.

We're also letting @erikmellum off the hook :) He's been gracious enough to donate his time to the customizer, but he's no longer contracting with us. So you can direct all customizer issues to myself, @rafibomb, and @kball.

If you want to see the updates for yourself, we have an open pull request with custom builds working: #8400

**Comment by Lynda333** [comment]
@gakimball - Thank you for the update! Glad to hear it. 

@erikmellum - You rock for the time you donated to help us that use Foundation and love the customizer!

**Comment by Lynda333** [comment]
@kball @gakimball 

I saw that #8400 was merged and the customizer is working again. Thank You!

Couple things I noticed: 

1) Vendor prefixes are missing. 

2) It appears flex properties are used, even if the normal grid is selected.

**Comment by kball** [comment]
Hi @Lynda333,

Thanks for taking a look!  

Looking at the normal grid selection, it looks like what's getting set still is the flex-basis on a number of classes, but display:flex etc are not.  Can you confirm this is what you're seeing?  @gakimball is that intended or unexpected?

On the vendor prefixes, @gakimball can you take a look at that?  It looks like maybe autoprefixer isn't in the customizer build pipeline?

**Comment by Silvester20** [comment]
Thanks for the amazing work!

**Comment by Lynda333** [comment]
@kball - Yes, that is what I'm seeing.

**Comment by Silvester20** [comment]
@kball @gakimball 

Btw, got an error when creating a new instance of an off-canvas wrapper (No errors at full download).
"Uncaught TypeError: Foundation.OffCanvas is not a constructor"

`var ofc  = new Foundation.OffCanvas($('#newOffcanvas'), {forceTop: false});`

**Comment by kball** [comment]
@Silvester20 Can you link to the page in question somewhere I can take a look?  I tried a complete download just now and had no issues instantiating a new offcanvas.

**Comment by Lynda333** [comment]
@kball @gakimball @rafibomb - Any updates on the customizer? Still seeing the same problems.

**Comment by Silvester20** [comment]
@kball About the Off Canvas check http://foundation.zurb.com/forum/posts/39376-off-canvas-missing-in-customized-js

**Comment by rafibomb** [comment]
Couple things appear to be fixed by @kball ! Fixed off-canvas not included with custom flex grid, fixed pagination not included in customizer.

**Comment by kball** [comment]
I believe I also fixed the flex & prefix issues reported by @Lynda333

**Comment by Lynda333** [comment]
@kball @rafibomb - Thank you! From what I see all appears fixed. If I run into any problems, I'll post them. :)

**Comment by karls77** [comment]
I still see no pagination class included in the css in the customizer. The menu-icon class is also missing from the css. But it's also serving up 6.2.0 and not 6.2.1 according to the comments in the css and js.

**Comment by Lynda333** [comment]
@karls77 - I just tried the download and I am seeing 6.2.1 in the comments as well as pagination classes and menu-icon classes in the CSS.

**Comment by Silvester20** [comment]
Seems off canvas is working too now, thanks!

**Comment by colin-marshall** [comment]
A user has reported issues with menu-icon in the custom and complete downloads.
https://github.com/zurb/foundation-sites/issues/8565

**Comment by joomlolo** [comment]
hello, 
Always the problem with "Choose Your Components:"
"All Foundation Components" checking or uncheking don't work
and another thing more important some flex settings are added to the grid even if flexbox is not selected,the same in the sass version


https://github.com/zurb/foundation-sites/issues/8501

**Comment by Benboe** [comment]
Is it "normal" that the tabs still don't seem to work? :-o

I custom downloaded, left all the boxes checked, I used the tabs code.. and it doesn't work.. I also see no plugins such as accordion in the vendor directory?

**Comment by colin-marshall** [comment]
@Benboe I cannot reproduce your issue. I just went to the customizer page, left everything selected as is, and downloaded. I added tabs code to `index.html` and they worked. What markup did you use for the tabs? Any errors in the console?

I don't think you're supposed to get the individual plugins in the vendor directory. The JS components you select in the customizer get concatenated into `foundation.js` and `foundation.min.js`.

**Comment by colin-marshall** [comment]
@JTallis I fixed the menu-icon class issue with #8608. I'm not totally sure when that will go into effect on the website. @kball?

**Comment by Benboe** [comment]
@colin-marshall  my bad! I think i was using old foundation5 code, it changed :-) thanks for checking!

But... it might be me.. but it seems can't enter any numeric values on the custom download page (for the 3 grid values)?

I'm using a macbook pro, tried with firefox and chrome.. 

the only work around is using firebug, updating the values that way

**Comment by Lynda333** [comment]
@Benboe - Changing the values works for me on Firefox and Chrome (using Windows 10).

**Comment by colin-marshall** [comment]
@kball: If I download only the flex-grid in the customizer with everything else unchecked I get the animation classes too. Is this a customizer bug or do these come standard in every customizer download? See #8806.

**Comment by kball** [comment]
@colin-marshall good question.  Looking at the template being used, it appears motion-ui transitions and animations are currently always being included, so this appears to be the intent. I'm not sure why - this seems like something that should be optional - So we could accept a PR that moved those from being a standard part of the template (see `SASS_TEMPLATE` variable in `customizer/lib/sass.js`) and into something configurable... we'd also need to change the UI in the customizer web app itself to handle this.

**Comment by inimist** [comment]
Wow, this issue is persisting for years now. The custom downloads for foundation components not working.  No easy programming guys at the foundation, the developers of great tool! Poor guys! :(

**Comment by rafibomb** [comment]
@kball @colin-marshall When F6 was released and customizer setup, Motion-ui was a dependency of many components. It may be optional now as Orbit can operate without it.

**Comment by webuxr** [comment]
@LDigital84 - Seems like the only remaining  unchecked box in your original post is now complete (#7820 marked closed). Does this mean #7033 can also be closed?

There’s an a lot of great work in this ticket and I think it would be awesome to see #7033 closed as well.

That is, if the original issue with Foundation download page/options/checkboxes, et. al. have been addressed.

**Comment by JeremyEnglert** [comment]
All issues here have been addressed. Closing.
