### ISSUE TITLE
6.2 Features

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites#7759]
Here's what we want to do for Foundation 6.2.0.

- [ ] Ship Joyride, which has already been written.
- [ ] ~~Ship Clearing, which still needs to be ported from Foundation 5.~~
- [x] Add flexbox modes to components #7757
  - [ ] Add flexbox option to customizer
- [ ] Update the JavaScript codebase to ES2015 #7758
  - [ ] Along with this, ship UMD bundles for components.
- [x] Flexible color palettes #7219 (specifically [this comment](https://github.com/zurb/foundation-sites/issues/7219#issuecomment-166990006))
- [x] `data-toggle-focus`, a variant of `data-toggle` that fires the events on element focus/blur instead of click. bf2cf1bb08d4238a48a5955ed10d01cb3ff54c39
- [x] `data-open`, `data-close`, and `data-toggle` can trigger multiple elements at once #7806
- [x] Upgrade the templates to Gulp 4 and ES6 zurb/foundation-zurb-template#28
  - [ ] We're collecting feeedback on the featureset of the ZURB Template at #7760
- [x] Place forms before buttons in the cascade. 9c2d18935c7d35c1ea603da3673e3993eb7c47a6
  - [ ] And test it thoroughly.
- [x] Port `<input type="range">`, `<progress>`, and `<meter>` styles from Foundation for Apps.

If you're interested in contributing, there's a `6.2` branch you can work on.

**Comment by zurbchris** [comment]
I think we should leave Gulp 4 out of the mix until it hits semver. The requirement to swap between 3.x and 4 is obnoxious if you're running multiple versions in different templates.

**Comment by gakimball** [comment]
@zurbchris Since we use npm scripts to run things, all of that is abstracted away. We avoid referencing the `gulp` command in our documentation in favor of `npm start`.

**Comment by andycochran** [comment]
There are some folks using `gulp watch` tho—like those of us using @JeremyEnglert's [JointsWP](http://jointswp.com/docs/gulp/). Would Gulp 4 effect us negatively?

**Comment by gakimball** [comment]
@andycochran I believe folks will need to switch over to the new `gulp-cli` module, which can run both 3.x and 4.x projects. We'll make sure to announce that in the release notes.

**Comment by JeremyEnglert** [comment]
Is 'gulp watch' going away in Gulp 4? I didn't see anything about that.

**Comment by gakimball** [comment]
@JeremyEnglert If you have a task called "watch" it will still work. One thing that did change in Gulp 4 is that you can have tasks that aren't exposed to the CLI.

```js
// Not seen by the CLI
function clean() {
}

// Can be run with "gulp build"
gulp.task('build', function() {
});
```

**Comment by phifa** [comment]
Why did you remove clearing from the list? It's a very important feature. Without it we have to keep using external libraries, like fancybox, lightbox, etc.

**Comment by gakimball** [comment]
@phifa We're trying to hit a ship date of February 26 so unfortunately we had to axe something.

**Comment by phifa** [comment]
will some sort of lightbox solution eventually be implemented?

**Comment by gakimball** [comment]
@phifa Yep, just at a later date. It's going to look something like [this](https://github.com/zurb/foundation-sites/issues/7823#issuecomment-170154950).

**Comment by gakimball** [comment]
Closing in favor of this open pull request: #8089

Has the side effect of giving me a free issue to close :)

**Comment by PhilipJohnBasile** [comment]
Why wasn't joyride included?

**Comment by gakimball** [comment]
@PhilipJohnBasile We have the code together, we just didn't have time to tie everything together. I think we can get it out in the next month, and since it's going to be a standalone plugin, it doesn't have to be bound to a Foundation release.

**Comment by meganedesigns** [comment]
@gakimball Any status on Joyride for Foundation 6?

**Comment by colin-marshall** [comment]
@meganedesigns: @kball & @rafibomb are now the people to contact about this.

**Comment by misteryyy** [comment]
Is there any update to this? :)

**Comment by rafibomb** [comment]
@meganedesigns There is a new version that is available to test available now. Let me know if you want to try it out and let us know how it goes. Email rafi at zurb .com

**Comment by phifa** [comment]
Hey @rafibomb @gakimball what is the status of the clearing plugin? There seem to be a lot of people interested in this...

**Comment by mbarwick83** [comment]
+1 for clearing and joyride.

**Comment by lchinke** [comment]
+1 for clearing ... really disgusting that remove

**Comment by alexivkin** [comment]
+1 for clearing... why, I mean, why did you forgo of it in 6? Too much support? Too complex? Too lazy?

**Comment by phifa** [comment]
+1 for clearing : check this out, this is how it is done! http://photoswipe.com/

**Comment by AlexLaforge** [comment]
+1 for Clearing

**Comment by Geo86** [comment]
+1 for clearing would be useful

**Comment by theodorocaliari** [comment]
+1 clearing and joyride permanently and stops cut off nice things in the foundation on every update... in the past is the orbit, ressurected in ver. 6, now are this 2 plugins... oh come on... our sites not can be updated if we use this resources and after foundation update they gone...

**Comment by awalias** [comment]
+1 for clearing

**Comment by ncoden** [comment]
Okay. Thank you. We understood. 👌 

A lot of people want the Clearing and Joyride component to be ported to Foundation 6. We understood, no need to add `+1` on this post, it lead to nothing except spamming people.

I will see with the others members of the core team if we can implement it and for when (maybe `6.4` ?). **Please do not reply on this issue**, we will open new issues to work on this and we will  poke you once it is released.

Nicolas
