### ISSUE TITLE
Version 6.2.1 priorities

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites#8413]
We've deliberately waited a little longer for this first patch to 6.2 so we could see what unfolds. Current rough timeline for release is "a few weeks from now".
- [x] Add precompiled JavaScript to `dist/` folder #8406
- [x] Verify foundation-zurb-template will work with Babel's es2015 preset unconfigured #8256 #8324
- [x] Resolve issues with migration to `$foundation-palette` #8281 #8292
- [x] Handle Babel errors in foundation-zurb-template better #8340
- [x] Flexbox mode issues #8325 #8409
- [x] **When 6.2.1 is released,** merge zurb/foundation-zurb-template#34

@andycochran @colin-marshall @JeremyEnglert Have y'alls seen anything critical specific to 6.2 that's worth addressing?

**Comment by JeremyEnglert** [comment]
The .babelrc seems to have caused a headache for a few people - so it's awesome to see precompiled JS being included. 

Is there a reason the .babelrc file is included in the bower version of Foundation - shouldn't users be configuring babel inside of their own build process? It makes sense for the foundation-template, but for the bower install, it seems to cause more issues than good. 

Also, since other topbar issues are going to be addressed, it may be worth knocking out this one as well: https://github.com/zurb/foundation-sites/issues/8272

**Comment by gakimball** [comment]
@JeremyEnglert We can drop that `.babelrc` from the package if it's creating an issue.

My goal is that you can load the `es2015` preset and not have to worry about anything. The *only* issue was with how the commonjs module interacted with what-input, but that's been resolved. Still need to do more testing, but I believe everything will be fine there. My [comment here](https://github.com/zurb/foundation-sites/issues/8256#issuecomment-191432692) breaks down that web of intersecting issues.

**Comment by colin-marshall** [comment]
@JeremyEnglert does babel "fallback" to the  `.babelrc` inside of the foundation-sites bower directory if there is not a `.babelrc` in the root directory of the project?

**Comment by brettsmason** [comment]
I've been investigating changing menus to `inline-block` as @JeremyEnglert linked to above. I also think it would be worth adding. I have it working and could submit a PR for this is of interest? I did need to add `floats` too though, because of the spacing issue with `inline-block`.

One plus of this though is I've managed to get a working mega menu which I see a lot of people ask for (though not sure how to handle it when it converts to drilldown - it doesn't work there yet).

Other than the JS compile errors I've not experienced any other issues myself :smile:

**Comment by brettsmason** [comment]
Oh also forgot an old issue of mine: [7770](https://github.com/zurb/foundation-sites/issues/7770)
Wondered if there was any way we could develop the accordion menu further? I'm happy to have a go, but need some guidance on the correct way to approach it!

**Comment by Silvester20** [comment]
The bug in the tooltip from https://github.com/zurb/foundation-sites/issues/8144 is still there in 6.2.0. So in my opinion this should be an argent fix in the next release.

**Comment by Silvester20** [comment]
Also a old bug with closeable callouts is present, refering to https://github.com/zurb/foundation-sites/issues/8428

And the range slider doesn't work for touch.

Seems to be very important issues to solve in the next release.

**Comment by andycochran** [comment]
@brettsmason No need to use `float` just because of `inline-block`. Check out how I updated Button Groups #7933. 

(Relatedly: I can't seem to find where, but I brought up the fact that it's kinda silly that Foundation has both Menus and Button Groups. They're functionally the same thing. Only difference is, a Menu's "buttons" aren't blue.)

**Comment by brettsmason** [comment]
@andycochran I know there is the `font-size: 0` on the parent container trick to remove the white space, but I'm sure I read this isn't cross browser supported, hence why I looked into floats.

**Comment by andycochran** [comment]
@brettsmason Ah, yeah. Android pre Jellybean. 

For Button Groups, @gakimball and I decided that making things better in every other browser was worth Android 2 taking a hit. https://github.com/zurb/foundation-sites/pull/7933#issuecomment-174628485

It may be the same case for Menus—which, as I keep pointing out, make Button Groups redundant.

**Comment by gakimball** [comment]
Hey friends, quick update—the team is heads down on launching Foundation for Emails 2 tomorrow morning, but we want to deploy 6.2.1 next Friday, April 1. We'll see about locking down a build to QA around next Wednesday or so.

**Comment by phifa** [comment]
the uncss issues might be more related to the zurb template https://github.com/zurb/foundation-zurb-template

**Comment by gakimball** [comment]
I tested the ZURB Template with the latest development build, and version 2.0 of what-input appears to solve many of the wild configuration issues we had with Babel. Now the template can just use the stock `es2015` preset as-is.

I have a branch [here](https://github.com/zurb/foundation-zurb-template/tree/v6.2.1) @colin-marshall if you have time could you take a look and see if this looks good? I want to solidify what the ZURB Template will look like for 6.2.1.

**Comment by colin-marshall** [comment]
@gakimball that looks and works fine for me, however I could not reproduce some of the issues people were having with babel in 6.2.0. Maybe @JeremyEnglert and the other people that had issues could also test it out?

Also, is there anything stopping us from putting `bower install` in an npm `postinstall` script so you only have to run `npm install`?

**Comment by gakimball** [comment]
@colin-marshall We could do that, although the CLI already runs `npm install && bower install` for you.

**Comment by JeremyEnglert** [comment]
@gakimball - looks good to me.

Is there any benefit to having a separate .babelrc opposed to adding the settings to the gulpfile?

```JAVASCRIPT
function javascript() {
  return gulp.src(PATHS.javascript)
    .pipe($.sourcemaps.init())
    .pipe($.babel({
        presets: ['es2015']
    }))
    .pipe($.concat('app.js'))
    .pipe($.if(PRODUCTION, $.uglify()
      .on('error', e => { console.log(e); })
    ))
    .pipe($.if(!PRODUCTION, $.sourcemaps.write()))
    .pipe(gulp.dest(PATHS.dist + '/assets/js'));
}
```

**Comment by gakimball** [comment]
@JeremyEnglert For the Gulpfile itself to work with ES6 you need the `.babelrc`.

**Comment by gakimball** [comment]
Oh the other thing I noticed is that the `.babelrc` in the Bower package itself does indeed cause problems, so it should be ignored in the npm and Bower package definitions if it's not already.

**Comment by JeremyEnglert** [comment]
> @JeremyEnglert For the Gulpfile itself to work with ES6 you need the .babelrc.

Ahhh right. I forget ES6 is only supported by Node 4+.

**Comment by gakimball** [comment]
Hey friends, 6.2.1 won't be shipping tomorrow unfortunately :< Ended up being a hectic week on our end. We'll check back in next week!

**Comment by Silvester20** [comment]
Thanks for letting us know, hope all of the awesome commits of @Owlbertz will be merged then.

**Comment by rafibomb** [comment]
6.2.1 is going out today! It wraps up all the great changes @gakimball put in on this issue as well as @Owlbertz. Thanks for the assists @colin-marshall , @andycochran and @JeremyEnglert !

**Comment by Silvester20** [comment]
@rafi This is great! Hope the slider issues fixed by @Owlbertz are inside the new version. Please update the custom download to v6.2.1 so I can do some testing.

**Comment by rafibomb** [comment]
@Silvester20 Have you had a chance to test https://github.com/zurb/foundation-sites/pull/8449 ? We'll have a quick turn around for 6.2.2 which we'll make sure that one gets into. More people confirming the fix helps!

**Comment by Silvester20** [comment]
@Rafi I am not fammiliar with Github, so I will wait for the js/css package update.

**Comment by hylke94** [comment]
Any progression on the list above? I need #8409 to be fixed soon...

**Comment by hylke94** [comment]
Any feedback, maybe?

@gakimball @kball

**Comment by kball** [comment]
We're making progress but some of these issues are still outstanding as we package up 6.3, moving the milestone out once again

**Comment by colin-marshall** [comment]
#8281, #8292, #8325, and #8409 are all closed. I checked off those boxes which completes the list  so I think it's safe to close this out now.
